### ISSUE TITLE
Internal server error on a given WMS doc

### ISSUE THREAD

**Issue by viddo** [omniscale/wmtsproxy#2]
The original WMS source: http://api.maps.vic.gov.au/vicmapapi-mercator/map-wm/wms?&request=GetCapabilities&service=WMS

When checked through the REST API like this `/check?url=http%3A%2F%2Fapi.maps.vic.gov.au%2Fvicmapapi-mercator%2Fmap-wm%2Fwms%3F%26request%3DGetCapabilities%26service%3DWMS&type=wms&callback=cb`

it yields:

```
cb({
"error": "internal server error"
})
```

This is the stack trace on that call:

```
2015-06-03 09:48:29,086 - ERROR - wmtsproxy_restapi.app - 'NoneType' object has no attribute 'findtext'
Traceback (most recent call last):
 File "/opt/mapproxy/lib/python2.7/site-packages/wmtsproxy_restapi/app.py", line 49, in list_layers
   cap = cap_dict(cap_url)
 File "/opt/mapproxy/lib/python2.7/site-packages/wmtsproxy/capabilities.py", line 63, in cap_dict
   return wms_cap_dict(cap)
 File "/opt/mapproxy/lib/python2.7/site-packages/wmtsproxy/capabilities.py", line 144, in wms_cap_dict
   'title': cap.metadata()['title'],
 File "/opt/mapproxy/lib/python2.7/site-packages/mapproxy/util/ext/wmsparse/parse.py", line 51, in metadata
   md['contact'] = self.parse_contact()
 File "/opt/mapproxy/lib/python2.7/site-packages/mapproxy/util/ext/wmsparse/parse.py", line 57, in parse_contact
   person = self.findtext(elem, 'ContactPersonPrimary/ContactPerson'),
 File "/opt/mapproxy/lib/python2.7/site-packages/mapproxy/util/ext/wmsparse/parse.py", line 28, in findtext
   return tree.findtext(self.resolve_ns(xpath))
AttributeError: 'NoneType' object has no attribute 'findtext'
```

Python is not my primary language unfortunately, but following the stack trace it looks like it's a problem on the mapproxy lib, but not sure if it's really because there's a bug there or the problem is higher up?

**Comment by olt** [comment]
The service doesn't have ContactInformation but the parser expected them. This is fixed in https://github.com/mapproxy/mapproxy/commit/564ecbead8d3fa93416f6b100a30a15a2072c07b

**Comment by viddo** [comment]
Wow, that was quick, thx a bunch! :)
